on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples:
    runs-on: ubuntu-latest
    env:
      ROC_VERSION: nightly
      ZIG_VERSION: 0.13.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install Build Essentials
        run: sudo apt install build-essential git

      - name: Install OpenGL
        run: sudo apt-get install -y libgl1-mesa-dev

      - name: Install Required Libs
        run: sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev

      - name: Install libtool
        run: sudo apt-get install -y libtool libtool-bin

      - name: Install raylib
        run: git submodule update --init --recursive

        # TODO install Rust and Cargo and check things...

      - name: Install ROC
        run: |
          # Install ROC
          curl -fOL https://github.com/roc-lang/roc/releases/download/${ROC_VERSION}/roc_nightly-linux_x86_64-latest.tar.gz
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      - name: Run all tests
        run: ROC=./roc_nightly/roc ./ci/all_tests.sh
